#!/bin/sh

. /etc/profile.d/otbenv.profile

export PATH=/opt/anaconda/bin:/opt/OTB:${PATH}

[ "$#" -ne 2 ] && exit 1

export PYTHONPATH=${PYTHONPATH}:/application/s1tiling/lib

mkdir -p $( dirname $2 ) 

python /application/s1tiling/lib/S1Processor.py $1 &> $2
